In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import linear_model
import imp

imp.reload(linear_model)

<module 'linear_model' from 'C:\\Users\\juhjoo\\Linear regression\\linear_model.py'>

In [100]:
df = pd.read_csv("test.csv")

In [101]:
df

x          y
0    77  79.775152
1    21  23.177279
2    22  25.609262
3    20  17.857388
4    36  41.849864
..   ..        ...
295  71  68.545888
296  46  47.334876
297  55  54.090637
298  62  63.297171
299  47  52.459467

[300 rows x 2 columns]

In [102]:
x = df["x"].values.reshape(-1, 1)
y = df["y"].values

In [103]:
lr = linear_model.LinearRegression(fit_intercept=True)

In [104]:
lr.fit(x, y)

In [105]:
lr._intercept

1.0143353551195182

In [106]:
lr._coef

array([-0.46181077,  1.01433536])

In [107]:
df_test = pd.read_csv("./train.csv")
df_test.head()
X_test = df["x"].values.reshape(-1,1)

In [108]:
lr.predict(X_test)[:5]

array([[77.64201157],
       [20.83923168],
       [21.85356704],
       [19.82489633],
       [36.05426201]])

In [110]:
df = pd.read_csv("mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [117]:
y = df["average_points_scored"].values
x = df.iloc[:, :4].values

In [121]:
lr = linear_model.LinearRegression(fit_intercept=False)

mu_x = np.mean(x, axis=0)
std_x = np.mean(x, axis=0)

rescaled_X = (x - mu_x) / std_x # rescaled

In [122]:
lr.fit(rescaled_X, y)

In [123]:
lr.coef

array([-24.30945415,   1.98540037,  21.53047611,   8.4356117 ])

In [124]:
lr.intercept

1.9854003719812559